### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by kossatov** [akaraulli/Oracle_Audit_Add_on_for_Graylog#1]
Hello, thank you very much for this product, and I used it for 2 months, but I had to update ORACLE db from 19.12 to 19.15 and sending logs stopped working for me.

here is the error
ORA-06502: PL/SQL: numeric or value error
ORA-06512: at “AUDORAGRAYLOG.ORACLE_GRAYLOG”, line 750 - RAISE;
ORA-06512: at “AUDORAGRAYLOG.ORACLE_GRAYLOG”, line 555 - v_GL_record :=
ORA-06512: at “AUDORAGRAYLOG.ORACLE_GRAYLOG”, line 555 - v_GL_record :=
ORA-06512: at line 1
could you help me to solve this problem

**Comment by akaraulli** [comment]
Hi
and thanks for reporting.

As I can see, you are failing at Package Body ORACLE_GRAYLOG, on the preparation of v_GK_record CLOB variable as below:

```
v_GL_record := 
'{' 

|| '"version":"1.1", '
........ 
```

The variable v_GL_record is of CLOB type, and as such I am not expecting an error of this type (06502) here. On the other side, Oracle says that the is nothing new from your old version 19.2 to the new one 19.5:
[](https://docs.oracle.com/en/database/oracle/oracle-database/19/newft/new-features-19c-release-updates.html)

At least so they say. You do not take this for granted. I have noticed that new (unified) audit fields contain dirty characters. That is the reason for the part of code:

-- Clear fields
```
v_sql_binds := replace(v_sql_binds,chr(0),'');
v_sql_text  := replace(v_sql_text,chr(0),'');
v_rls_info  := replace(v_rls_info,chr(0),'');
```

So what is left is to determine the exact line of failure. First I suggest you create copy of the procedure inside the package, and call it directly. In this copy procedure you can try to determine the exact failing line by:

1. Comment all lines of v_GL_record content concatenation and un-comment them one by one (or in groups) to determine which exact line is failing
2. try to use try DBMS_UTILITY.FORMAT_ERROR_BACKTRACE as described in the link below:
[](https://stackoverflow.com/questions/1589252/is-there-a-way-to-get-the-line-number-where-an-exception-was-thrown)
3. open a ticket at Oracle if you have support there, or ate least at their community

best regards
Altin

**Comment by kossatov** [comment]
I commented out this line and the procedure worked.
-- || '"_SQL_TEXT":"'             || v_sql_text                  || '", '
but here is the most interesting, I removed the comments and saved the procedure also remained to work.

**Comment by kossatov** [comment]
Thanks for your help, but I still don't understand what the problem is.

**Comment by akaraulli** [comment]
thank you for testing and reporting.

Did you try with the same set of records? Or did you skipped problematic set of records and were successful with next ones?
Because if this later - this means that not only there is something in the SQL_TEXT that is causing the problem, but what is worse, this "something" is not present in all kind records - but only in some of them.

Have you been able to determine if the error occurs for all ACTION_NAME-s - or only for some, and which ones?
Obviously, this will mean that the error will come out again, when the "bad" condition will pop-out again.

best regards
Altin
